frase = 'Curso em Vídeo Python  '
print(frase.replace('Python', 'Java'))
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.split())
print(''.join(frase))
print(frase.lower().find('vídeo'))