frase = 'Curso em Vídeo Python'
print(frase)
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(len(frase))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.lower())
print('Curso' in frase)
